name: New Bug report
description: Report a bug.
labels: 'bug'
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to report an EssentialsX bug! Fill out the form below to provide us with info to help fix the bug.
      Only use this if you're 100% sure you've found a bug and can reproduce it. If you're looking for general help with EssentialsX, try the Q&A forum or MOSS Discord server.

- type: input
  attributes:
    label: "`/towny version` output"
    description: Run `/towny version` in the console, then copy and paste the full output of the command into this box.
  validations:
    required: true
- type: input
  attributes:
    label: "`/version` output"
    description: Run `/version` in the console, then copy and paste the full output of the command into this box.
  validations:
    required: true
- type: input
  attributes:
    label: Server startup log
    description: Upload your server startup log (from the start of `latest.log` up to where it says "Done!") to either https://paste.gg or https://gist.github.com, save and then paste the link in this box.
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"
  validations:
    required: true
- type: input
  attributes:
    label: Towny config file
    description: Upload your Towny `config.yml` to either https://paste.gg or https://gist.github.com, save and then paste the link in this box. If you included those files in the same paste as your startup log, paste the same link here.
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"
  validations:
    required: true
- type: input
  attributes:
    label: townyperms.yml file
    description: Upload your Towny `townyperms.yml` to either https://paste.gg or https://gist.github.com, save and then paste the link in this box. If you included those files in the same paste as your startup log, paste the same link here.
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"
  validations:
    required: true
- type: input
  attributes:
    label: Your log's error 
    description: If you are reporting a console error, upload any relevant log excerpts to either https://paste.gg or https://gist.github.com, save and the paste the link in this box. If you included those files in the same paste as your startup log, paste the same link here.
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"
- type: input
  attributes:
    label: Your permission plugin's file (optional)
    description: If this has to do with permissions upload your permission plugins file to either https://paste.gg or https://gist.github.com, save and then paste the link in this box. If you included those files in the same paste as your startup log, paste the same link here.
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"
- type: input
  attributes:
    label: Your chatconfig.yml (optional)
    description: If this has to do with chat, upload your chatconfig.yml file to either https://paste.gg or https://gist.github.com, save and then paste the link in this box. If you included those files in the same paste as your startup log, paste the same link here.
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"
- type: input
  attributes:
    label: Your channels.yml (optional)
    description: If this has to do with chat, upload your channels.yml file to either https://paste.gg or https://gist.github.com, save and then paste the link in this box. If you included those files in the same paste as your startup log, paste the same link here.
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"


- type: textarea
  attributes:
    label: Bug description
    description: Describe roughly what the bug is here.
    placeholder: |
      Example: "When I added someone to my town they could build and break everything."
  validations:
    required: true
- type: textarea
  attributes:
    label: What steps will reproduce the problem?
    description: Provide an example of how to trigger the bug.
    placeholder: |
      Example:
      1. 
      2. 
      3. 
  validations:
    required: true
- type: textarea
  attributes:
    label: What is the expected behaviour?
    description: Explain what you should expect to happen.
    placeholder: |
      Example:
      1. 
      2. 
      3. 
  validations:
    required: true
