name: Publish to Glare Repo
on:
  workflow_dispatch:
#on: 
#  released:
#    type: [release,prerelease]

jobs:
  deploy_to_glare_repo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    name: mvn deploy @ glare repo
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: set up eclipse temurin
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          java-package: jdk
          cache: 'maven'
      - name: maven-settings-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: |
            [{
              "id": "nexus",
              "username": "${{ secrets.GLAREREPO_USERNAME }}",
              "password": "${{ secrets.GLAREREPO_PASSWORD }}"
            }]
          active_profiles: |
            [
              "nexus"
            ]
      - run: mvn deploy
